test json validation

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,8 +21,15 @@ jobs:
         run: |
           echo "Fetching data from API..."
           FILE_NAME=$(date +'%Y%m%d%H%M').json
-          curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en" > $FILE_NAME
-          echo "Data saved to data.json"
+          curl -s "example.com" > $FILE_NAME
+      - name: Validate JSON file
+        run: |
+          if jq empty "${{ env.FILE_NAME }}"; then
+             echo "✅ JSON validation passed: data successful"
+          else
+             echo "❌ JSON validation failed"
+             exit 1
+    fi
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v5
         with:
